"""SQLAlchemy declarative base and shared column helpers.

`db/` is the persistence *implementation detail* underneath the
competition rules (ARCHITECTURE.md §1). ORM classes here are a separate
set of types from `app/domain/models.py` — they are never the same
class, and the domain layer never imports from `app.db`. Translation
happens explicitly in `app/db/mappers/`.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase, mapped_column
from sqlalchemy.types import DateTime

# A fixed naming convention so autogenerated Alembic migrations produce
# stable, predictable constraint names instead of driver-assigned ones.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    # Every plain `Mapped[datetime]` / `Mapped[datetime | None]` column
    # maps to a timezone-aware TIMESTAMPTZ by default. Without this,
    # SQLAlchemy's default `datetime` mapping is naive
    # TIMESTAMP WITHOUT TIME ZONE, which silently strips tzinfo on
    # round-trip — every timestamp in this schema (kickoff, checkpoint
    # windows, snapshot/settlement times...) is meaningless without a
    # timezone, and DATABASE.md specifies TIMESTAMPTZ throughout.
    type_annotation_map = {datetime: DateTime(timezone=True)}


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def uuid_pk():
    """A UUID primary key column, generated application-side (not
    DB-side) so a freshly-constructed ORM object always has its id
    available before flush, which the mapper layer relies on."""

    return mapped_column(primary_key=True, default=uuid.uuid4)


def created_at_column():
    return mapped_column(DateTime(timezone=True), default=utcnow, nullable=False)
