"""structural core

Revision ID: 7ca45891cafe
Revises: 
Create Date: 2026-09-13 02:33:40.074020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ca45891cafe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors'))
    )
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_players_external_ref'))
    )
    op.create_table('seasons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','COMPLETE')", name=op.f('ck_seasons_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    op.create_table('games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_games_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('external_ref', name=op.f('uq_games_external_ref'))
    )
    op.create_table('season_competitors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_id', sa.String(), nullable=False),
    sa.Column('model_identifier', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','BUSTED')", name=op.f('ck_season_competitors_valid_status')),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_season_competitors_competitor_id_competitors')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_season_competitors_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season_competitors')),
    sa.UniqueConstraint('season_id', 'competitor_id', name='one_instance_per_season')
    )
    op.create_table('season_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('rules_version', sa.String(), nullable=False),
    sa.Column('starting_bankroll_cents', sa.BigInteger(), nullable=False),
    sa.Column('canonical_sportsbook', sa.String(), nullable=False),
    sa.Column('research_settlement_provider', sa.String(), nullable=False),
    sa.Column('research_settlement_delay_hours', sa.Integer(), nullable=False),
    sa.Column('supported_prop_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('devig_method', sa.String(), nullable=False),
    sa.Column('benchmark_slate_size', sa.Integer(), nullable=False),
    sa.Column('batch_methodology', sa.String(), nullable=False),
    sa.Column('checkpoint_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kelly_fraction', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('standard_max_bankroll_fraction', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('exceptional_max_bankroll_fraction', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('minimum_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('stake_increment_cents', sa.BigInteger(), nullable=False),
    sa.Column('pounce_limit', sa.Integer(), nullable=False),
    sa.Column('attribution_confidence_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weekly_decision_deadline_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competition_requires_nonpushable_line', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('amendment_reason', sa.String(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_season_rules_season_id_seasons')),
    sa.ForeignKeyConstraint(['superseded_by'], ['season_rules.id'], name=op.f('fk_season_rules_superseded_by_season_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season_rules')),
    sa.UniqueConstraint('rules_version', name=op.f('uq_season_rules_rules_version'))
    )
    op.create_table('weeks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('is_real_money', sa.Boolean(), nullable=False),
    sa.Column('counts_toward_standings', sa.Boolean(), nullable=False),
    sa.Column('counts_toward_awards', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('research_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_weeks_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weeks')),
    sa.UniqueConstraint('season_id', 'week_number', name='season_week_number')
    )
    op.create_table('benchmark_slate_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('target_slot_count', sa.Integer(), nullable=False),
    sa.Column('allocation_method', sa.String(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_benchmark_slate_plans_week_id_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_slate_plans')),
    sa.UniqueConstraint('week_id', name=op.f('uq_benchmark_slate_plans_week_id'))
    )
    op.create_table('checkpoint_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_type', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_checkpoint_runs_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkpoint_runs')),
    sa.UniqueConstraint('game_id', 'checkpoint_type', name='one_run_per_game_checkpoint')
    )
    op.create_table('competition_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_competition_events_season_competitor_id_season_competitors')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_competition_events_season_id_seasons')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_competition_events_week_id_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_events'))
    )
    op.create_index('ix_competition_events_competitor_timestamp', 'competition_events', ['season_competitor_id', 'timestamp'], unique=False)
    op.create_index('ix_competition_events_season_timestamp', 'competition_events', ['season_id', 'timestamp'], unique=False)
    op.create_index('ix_competition_events_week_timestamp', 'competition_events', ['week_id', 'timestamp'], unique=False)
    op.create_table('prop_markets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('stat_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_prop_markets_game_id_games')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_prop_markets_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prop_markets'))
    )
    op.create_table('benchmark_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('target_stat_type', sa.String(), nullable=False),
    sa.Column('fallback_stat_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_market_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_benchmark_slots_game_id_games')),
    sa.ForeignKeyConstraint(['plan_id'], ['benchmark_slate_plans.id'], name=op.f('fk_benchmark_slots_plan_id_benchmark_slate_plans')),
    sa.ForeignKeyConstraint(['resolved_market_id'], ['prop_markets.id'], name=op.f('fk_benchmark_slots_resolved_market_id_prop_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_slots')),
    sa.UniqueConstraint('plan_id', 'slot_index', name='one_slot_per_index')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('canonical_sportsbook', sa.String(), nullable=False),
    sa.Column('canonical_line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('canonical_over_price', sa.Integer(), nullable=True),
    sa.Column('canonical_under_price', sa.Integer(), nullable=True),
    sa.Column('canonical_over_probability', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('canonical_under_probability', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('devig_method', sa.String(), nullable=False),
    sa.Column('same_line_consensus_over_probability', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('market_median_line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('market_min_line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('market_max_line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('number_of_books', sa.Integer(), nullable=False),
    sa.Column('is_valid_canonical_baseline', sa.Boolean(), nullable=False),
    sa.CheckConstraint('canonical_over_probability IS NULL OR (canonical_over_probability >= 0 AND canonical_over_probability <= 1)', name=op.f('ck_market_snapshots_canonical_over_probability_range')),
    sa.CheckConstraint('canonical_under_probability IS NULL OR (canonical_under_probability >= 0 AND canonical_under_probability <= 1)', name=op.f('ck_market_snapshots_canonical_under_probability_range')),
    sa.CheckConstraint('same_line_consensus_over_probability IS NULL OR (same_line_consensus_over_probability >= 0 AND same_line_consensus_over_probability <= 1)', name=op.f('ck_market_snapshots_consensus_probability_range')),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_market_snapshots_market_id_prop_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots'))
    )
    op.create_table('prop_quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('sportsbook', sa.String(), nullable=False),
    sa.Column('line', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('over_price', sa.Integer(), nullable=False),
    sa.Column('under_price', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_prop_quotes_market_id_prop_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prop_quotes'))
    )
    op.create_table('research_settlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('research_stat_value_at_lock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('research_locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('later_corrected_stat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('correction_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_research_settlements_market_id_prop_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_settlements')),
    sa.UniqueConstraint('market_id', name=op.f('uq_research_settlements_market_id'))
    )
    op.create_table('evidence_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_run_id', sa.Uuid(), nullable=True),
    sa.Column('checkpoint_type', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_snapshot_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['checkpoint_run_id'], ['checkpoint_runs.id'], name=op.f('fk_evidence_snapshots_checkpoint_run_id_checkpoint_runs')),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_evidence_snapshots_market_id_prop_markets')),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], name=op.f('fk_evidence_snapshots_market_snapshot_id_market_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_snapshots'))
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_identifier', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('evidence_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('market_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('bankroll_at_decision_cents', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], name=op.f('fk_agent_sessions_evidence_snapshot_id_evidence_snapshots')),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], name=op.f('fk_agent_sessions_market_snapshot_id_market_snapshots')),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_agent_sessions_season_competitor_id_season_competitors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sessions'))
    )
    op.create_table('agent_session_evidence_snapshots',
    sa.Column('agent_session_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], name=op.f('fk_agent_session_evidence_snapshots_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], name=op.f('fk_agent_session_evidence_snapshots_evidence_snapshot_id_evidence_snapshots')),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_agent_session_evidence_snapshots_market_id_prop_markets')),
    sa.PrimaryKeyConstraint('agent_session_id', 'evidence_snapshot_id', name=op.f('pk_agent_session_evidence_snapshots'))
    )
    op.create_table('forecast_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('checkpoint_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_probability_over', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('canonical_market_probability_over', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('same_line_consensus_probability_over', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('canonical_line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('canonical_over_price', sa.Integer(), nullable=True),
    sa.Column('canonical_under_price', sa.Integer(), nullable=True),
    sa.Column('market_median_line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('probability_disagreement', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('uncertainty', sa.String(), nullable=False),
    sa.Column('evidence_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('revision_parent_id', sa.Uuid(), nullable=True),
    sa.Column('revision_reason', sa.String(), nullable=True),
    sa.Column('research_eligible', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(), nullable=True),
    sa.Column('agent_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('canonical_market_probability_over IS NULL OR (canonical_market_probability_over >= 0 AND canonical_market_probability_over <= 1)', name=op.f('ck_forecast_observations_canonical_probability_range')),
    sa.CheckConstraint('confidence >= 1 AND confidence <= 10', name=op.f('ck_forecast_observations_confidence_range')),
    sa.CheckConstraint('model_probability_over >= 0 AND model_probability_over <= 1', name=op.f('ck_forecast_observations_probability_range')),
    sa.CheckConstraint('same_line_consensus_probability_over IS NULL OR (same_line_consensus_probability_over >= 0 AND same_line_consensus_probability_over <= 1)', name=op.f('ck_forecast_observations_consensus_probability_range')),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], name=op.f('fk_forecast_observations_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], name=op.f('fk_forecast_observations_evidence_snapshot_id_evidence_snapshots')),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_forecast_observations_market_id_prop_markets')),
    sa.ForeignKeyConstraint(['revision_parent_id'], ['forecast_observations.id'], name=op.f('fk_forecast_observations_revision_parent_id_forecast_observations')),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_forecast_observations_season_competitor_id_season_competitors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_observations'))
    )
    op.create_table('pass_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('best_available_candidate_market_id', sa.Uuid(), nullable=True),
    sa.Column('estimated_edge', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('uncertainty', sa.String(), nullable=True),
    sa.Column('reason_for_pass', sa.String(), nullable=False),
    sa.Column('agent_session_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], name=op.f('fk_pass_decisions_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['best_available_candidate_market_id'], ['prop_markets.id'], name=op.f('fk_pass_decisions_best_available_candidate_market_id_prop_markets')),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_pass_decisions_season_competitor_id_season_competitors')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_pass_decisions_week_id_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pass_decisions')),
    sa.UniqueConstraint('season_competitor_id', 'week_id', name='one_pass_per_competitor_per_week')
    )
    op.create_table('stake_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('forecast_observation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_session_id', sa.Uuid(), nullable=True),
    sa.Column('bankroll_at_decision_cents', sa.BigInteger(), nullable=False),
    sa.Column('model_probability_over', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('canonical_market_probability_over', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('estimated_edge', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('kelly_fraction_used', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('kelly_reference_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('model_requested_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('risk_posture', sa.String(), nullable=False),
    sa.Column('final_allowed_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], name=op.f('fk_stake_recommendations_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['forecast_observation_id'], ['forecast_observations.id'], name=op.f('fk_stake_recommendations_forecast_observation_id_forecast_observations')),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_stake_recommendations_market_id_prop_markets')),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_stake_recommendations_season_competitor_id_season_competitors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stake_recommendations'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('stake_recommendation_id', sa.Uuid(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('risk_posture', sa.String(), nullable=False),
    sa.Column('kelly_reference_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('model_requested_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('final_allowed_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('observed_line', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('observed_price', sa.Integer(), nullable=True),
    sa.Column('market_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('acceptable_line_boundary', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('worst_acceptable_price', sa.Integer(), nullable=True),
    sa.Column('why_now', sa.String(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_tickets_market_id_prop_markets')),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], name=op.f('fk_tickets_market_snapshot_id_market_snapshots')),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_tickets_season_competitor_id_season_competitors')),
    sa.ForeignKeyConstraint(['stake_recommendation_id'], ['stake_recommendations.id'], name=op.f('fk_tickets_stake_recommendation_id_stake_recommendations')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_tickets_week_id_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_table('wagers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('requested_stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.Column('sportsbook', sa.String(), nullable=True),
    sa.Column('actual_line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('actual_price', sa.Integer(), nullable=True),
    sa.Column('actual_stake_cents', sa.BigInteger(), nullable=True),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bankroll_at_execution_cents', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['prop_markets.id'], name=op.f('fk_wagers_market_id_prop_markets')),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_wagers_season_competitor_id_season_competitors')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_wagers_ticket_id_tickets')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_wagers_week_id_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wagers')),
    sa.UniqueConstraint('ticket_id', name=op.f('uq_wagers_ticket_id'))
    )
    op.create_table('bankroll_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_competitor_id', sa.Uuid(), nullable=False),
    sa.Column('week_id', sa.Uuid(), nullable=True),
    sa.Column('wager_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_competitor_id'], ['season_competitors.id'], name=op.f('fk_bankroll_transactions_season_competitor_id_season_competitors')),
    sa.ForeignKeyConstraint(['wager_id'], ['wagers.id'], name=op.f('fk_bankroll_transactions_wager_id_wagers')),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], name=op.f('fk_bankroll_transactions_week_id_weeks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bankroll_transactions'))
    )
    op.create_table('settlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wager_id', sa.Uuid(), nullable=False),
    sa.Column('sportsbook_result', sa.String(), nullable=False),
    sa.Column('sportsbook_payout_cents', sa.BigInteger(), nullable=False),
    sa.Column('sportsbook_settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wager_id'], ['wagers.id'], name=op.f('fk_settlements_wager_id_wagers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements')),
    sa.UniqueConstraint('wager_id', name=op.f('uq_settlements_wager_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlements')
    op.drop_table('bankroll_transactions')
    op.drop_table('wagers')
    op.drop_table('tickets')
    op.drop_table('stake_recommendations')
    op.drop_table('pass_decisions')
    op.drop_table('forecast_observations')
    op.drop_table('agent_session_evidence_snapshots')
    op.drop_table('agent_sessions')
    op.drop_table('evidence_snapshots')
    op.drop_table('research_settlements')
    op.drop_table('prop_quotes')
    op.drop_table('market_snapshots')
    op.drop_table('benchmark_slots')
    op.drop_table('prop_markets')
    op.drop_index('ix_competition_events_week_timestamp', table_name='competition_events')
    op.drop_index('ix_competition_events_season_timestamp', table_name='competition_events')
    op.drop_index('ix_competition_events_competitor_timestamp', table_name='competition_events')
    op.drop_table('competition_events')
    op.drop_table('checkpoint_runs')
    op.drop_table('benchmark_slate_plans')
    op.drop_table('weeks')
    op.drop_table('season_rules')
    op.drop_table('season_competitors')
    op.drop_table('games')
    op.drop_table('seasons')
    op.drop_table('players')
    op.drop_table('competitors')
    # ### end Alembic commands ###
