"""agent session lifecycle

Revision ID: a8d1acc96058
Revises: 7ca45891cafe
Create Date: 2026-09-13 03:18:34.116572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8d1acc96058'
down_revision: Union[str, Sequence[str], None] = '7ca45891cafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` on `status` covers the (currently hypothetical, since
    # this table has no production rows yet) case of adding a NOT NULL
    # column to an already-populated table; `orchestration_key` is left
    # without one deliberately - a real deployment with existing rows
    # would need a considered backfill, not a synthetic default.
    op.add_column('agent_sessions', sa.Column('status', sa.String(), nullable=False, server_default='PENDING'))
    op.add_column('agent_sessions', sa.Column('orchestration_key', sa.String(), nullable=False))
    op.add_column('agent_sessions', sa.Column('rendered_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_sessions', sa.Column('provider_request_id', sa.String(), nullable=True))
    op.add_column('agent_sessions', sa.Column('usage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_sessions', sa.Column('error_category', sa.String(), nullable=True))
    op.add_column('agent_sessions', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('agent_sessions', sa.Column('transport_retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agent_sessions', sa.Column('correction_retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('agent_sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('agent_sessions', 'status', server_default=None)
    op.alter_column('agent_sessions', 'transport_retry_count', server_default=None)
    op.alter_column('agent_sessions', 'correction_retry_count', server_default=None)
    op.alter_column('agent_sessions', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('agent_sessions', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint('one_session_per_orchestration_key', 'agent_sessions', ['orchestration_key'])
    op.create_check_constraint(
        'valid_status', 'agent_sessions',
        "status IN ('PENDING','CALLING','VALID','INVALID','FAILED')",
    )
    op.create_check_constraint(
        'valid_error_category', 'agent_sessions',
        "error_category IS NULL OR error_category IN ("
        "'AUTHENTICATION_ERROR','RATE_LIMITED','TIMEOUT','PROVIDER_UNAVAILABLE',"
        "'INVALID_PROVIDER_RESPONSE','SCHEMA_VALIDATION_FAILED','CONTENT_REFUSAL','UNKNOWN_PROVIDER_ERROR')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('valid_error_category', 'agent_sessions', type_='check')
    op.drop_constraint('valid_status', 'agent_sessions', type_='check')
    op.drop_constraint('one_session_per_orchestration_key', 'agent_sessions', type_='unique')
    op.alter_column('agent_sessions', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('agent_sessions', 'raw_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('agent_sessions', 'completed_at')
    op.drop_column('agent_sessions', 'correction_retry_count')
    op.drop_column('agent_sessions', 'transport_retry_count')
    op.drop_column('agent_sessions', 'error_message')
    op.drop_column('agent_sessions', 'error_category')
    op.drop_column('agent_sessions', 'usage_metadata')
    op.drop_column('agent_sessions', 'provider_request_id')
    op.drop_column('agent_sessions', 'rendered_request')
    op.drop_column('agent_sessions', 'orchestration_key')
    op.drop_column('agent_sessions', 'status')
    # ### end Alembic commands ###
